[[sync-performance-scaling-guide]]
= Sync Performance & Scaling Guide

== Configure sync frequency of cloud apps

You can configure separate sync frequency in the client and cloud apps. In this section, we will focus on how to decide the best value for sync frequency of cloud apps.

The sync frequency value of a cloud app will determine how often the sync processor runs. It is the time the system should wait between 2 sync processors. Every time when a sync processor is being exectued, it will perform a list operation on the backend database/service to synchronize the data with a local copy. To determine the best value of the sync frequency, here are the few things you should consider:

how quickly do you want your clients to see changes from others?::

When a client submits changes, those changes are performed against the backend database/service directly. However, for other clients, they are getting the data from the local copy due to performance reasons. This means other clients will only be able to get the new changes after the next sync processor runs. If it's important for other clients to see the changes as soon as possible, then you should consider set a low value for the sync frequency.

how long it takes for each sync processor to run?::

As mentioned above, the frequency value will decide how long the system should wait between sync processor requests. It worth pointing out that it is the time from the completion of the first processor, to the start time of the second processor. This means it will never have a situation where 2 sync processors will be running at the same time. It also means:

  sync request process time = the time of each sync processor run + the value of sync frequency

+
This will help you to calculate the number of requests the system will make to the backend.
+
To know how long each sync processor run takes, you can query the sync stats endpoint to see the average `Job Process Time` it takes for the `sync_worker` to complete.

how much load can the backend service handle?::

As mentioned above, everytime when the sync processor runs, it will perform a list operation on the backend database/service. When you setup the sync frequency, you should be able to estimate how many requests it will generates to your backend, and make sure the backend can handle the load.
+
For example, if you set the sync frequency of a dataset to be 100ms, and each sync processor is taking 100ms to run, that means the cloud app will generate about 5 req/sec to your backend. However, if you have another dataset with the same frequency that uses the same backend, it means there will be about 10 req/sec to the backend. The rate will be fairly consistent, so you can perform so load tests against the backend to determine if the backend can handle that much load.
+
However, it worth mentioning that this value will not grow when you scale the app. This is by design to protect the backend when the app is under heavy load.

how much extra load it will cause to the cloud app itself?::

When the data is returned from the backend, the cloud app will have to save the data to the local storage (MongoDB). The system is smart enough to only perform updates if there are changes. But it needs to perform a read operation first to get the current data in the local storage first. When there are a lot of sync processors runs, it could cause extra load on the cloud app itself. Sometimes you may need to take this into consideration especially if the dataset's size is relatively large.
+
To understand performance of the cloud app, you can use the sync stats endpoint to check the CPU usages, and the MongoDB operation time to determine if the cloud app is under heavy load.

To summaries, you can use the sync frequency value to control the number of requests the cloud app will generate to your backend. It is perfectly fine to set it to 0, as long as the backend can handle the load, and the cloud app itself is not over-loaded.

== Scaling on OpenShift

The best way to scale the application on OpenShift is to use the auto scaling feature. In order to do that, you first have to make sure metrics is enabled in the OpenShift cluster, and then use the `oc autoscale` command to configure when the application should be scaled.

For example, on OpenShift 3.2, here is the document of how to https://docs.openshift.com/enterprise/3.2/install_config/cluster_metrics.html#metrics-deployer[enable cluster metrics]. Then here is how to https://docs.openshift.com/enterprise/3.2/dev_guide/pod_autoscaling.html#dev-guide-pod-autoscaling[scale the application].