[[sync-upgrade-guide]]
= Server SDK Upgrade Guide

== Overview

This guide is intedend for developers who:
* are using the Sync Server in their application
* and are upgrading the version of `fh-mbaas-api` from `<7.0.0` to `>=7.0.0`

If you are already using `fh-mbaas-api@>=7.0.0`, there is no need to go through this guide.

Note: There are *no* changes to the Sync Client as part of this upgrade.

== Prerequisites

Prior to `7.0.0` the Sync Server used the `fh.db` API to store sync operational data in MongoDB.
`fh.db` is a wrapper around MongoDB that may go through an intermediate http API (fh-ditch).
This made for a resticted set of actions that can be preformed on the sync operational data.
It also limited the potential use of modules that connect directly to MongoDB.
As of `fh-mbaas-api@7.0.0`, the Sync Server will require a direct connection to MongoDB.
This means:
* for a Dynofarm based Environment you will need to 'Upgrade' your App Database
* for an OpenShift based Environment, no action is required as all Apps get their own Database in MongoDB by default

== Data Handler function signature changes

The method signature for sync data handlers have changed.
If you have implemented/overriden any data handler, you will need to change the parameter ordering.
These changes are to conform to the convention in javascript, having a callback as the last parameter.
Here is the full list of data handlers and their signature prior to and as of `7.0.0`.

```js
// <7.0.0
sync.handleList(dataset_id, function(dataset_id, params, callback, meta_data) {});
sync.globalHandleList(function(dataset_id, params, callback, meta_data) {});
// >=7.0.0
sync.handleList(dataset_id, function(dataset_id, params, meta_data, callback) {});
sync.globalHandleList(function(dataset_id, params, meta_data, callback) {});


// <7.0.0
sync.handleCreate(dataset_id, function(dataset_id, data, callback, meta_data) {});
sync.globalHandleCreate(function(dataset_id, data, callback, meta_data) {});
// >=7.0.0
sync.handleCreate(dataset_id, function(dataset_id, data, meta_data, callback) {});
sync.globalHandleCreate(function(dataset_id, data, meta_data, callback) {});


// <7.0.0
sync.handleRead(dataset_id, function(dataset_id, uid, callback, meta_data) {});
sync.globalHandleRead(function(dataset_id, uid, callback, meta_data) {});
// >=7.0.0
sync.handleRead(dataset_id, function(dataset_id, uid, meta_data, callback) {});
sync.globalHandleRead(function(dataset_id, uid, meta_data, callback) {});


// <7.0.0
sync.handleUpdate(dataset_id, function(dataset_id, uid, data, callback, meta_data) {});
sync.globalHandleUpdate(function(dataset_id, uid, data, callback, meta_data) {});
// >=7.0.0
sync.handleUpdate(dataset_id, function(dataset_id, uid, data, meta_data, callback) {});
sync.globalHandleUpdate(function(dataset_id, uid, data, meta_data, callback) {});


// <7.0.0
sync.handleDelete(dataset_id, function(dataset_id, uid, callback, meta_data) {});
sync.globalHandleDelete(function(dataset_id, uid, callback, meta_data) {});
// >=7.0.0
sync.handleDelete(dataset_id, function(dataset_id, uid, meta_data, callback) {});
sync.globalHandleDelete(function(dataset_id, uid, meta_data, callback) {});


// <7.0.0
sync.handleCollision(dataset_id, function(dataset_id, hash, timestamp, uid, pre, post, meta_data) {});
sync.globalHandleCollision(function(dataset_id, hash, timestamp, uid, pre, post, meta_data) {});
// >=7.0.0  Adding a callback to the end of the arguments
sync.handleCollision(dataset_id, function(dataset_id, hash, timestamp, uid, pre, post, meta_data, callback) {});
sync.globalHandleCollision(function(dataset_id, hash, timestamp, uid, pre, post, meta_data, callback) {});


// <7.0.0
sync.listCollisions(dataset_id, function(dataset_id, callback, meta_data) {});
sync.globalListCollisions(function(dataset_id, callback, meta_data) {});
// >=7.0.0
sync.listCollisions(dataset_id, function(dataset_id, meta_data, callback) {});
sync.globalListCollisions(function(dataset_id, meta_data, callback) {});


// <7.0.0
sync.removeCollision(dataset_id, function(dataset_id, collision_hash, callback, meta_data) {});
sync.globalRemoveCollision(function(dataset_id, collision_hash, callback, meta_data) {});
// >=7.0.0
sync.removeCollision(dataset_id, function(dataset_id, collision_hash, meta_data, callback) {});
sync.globalRemoveCollision(function(dataset_id, collision_hash, meta_data, callback) {});
```

== Behaviour differences

As the sync server now connects directly to MongoDB, there is some setup time required on startup.
If you currently use `sync.init()`, you should wrap these calls in a `sync:ready` event handler.
For example, if this is you current code:

```js
fh.sync.init('mydataset', options, callback);
```

You should put it in an event handler.

```js
fh.events.on('sync:ready', function syncReady() {
  sync.init('mydataset', options, callback);
});
```

Or you can get the event emitter from the sync API
```js
fh.sync.getEventEmitter().on('sync:ready', function syncReady() {
  sync.init('mydataset', options, callback);
});
```

== Logger changes

The `logLevel` option that can be passed into `fh.sync.init()` is no longer available.
By default, the Sync Server will not log anything.
All logging is done using the [debug](https://www.npmjs.com/package/debug) module.
If you want log output from the Sync Server, you can set the `DEBUG` environment variable.
For example:

```shell
DEBUG=fh-mbaas-api:sync
```

To see all logs from the entire SDK, you can use
```shell
DEBUG=fh-mbaas-api:*
```

All other environment variables & behaviour of the `debug` module can be used if needed.
